### PR TITLE
not quite done, but launch GUI before client

### PR DESCRIPTION
**Pull request by STPv22**
the  launch on crash didn't work, and I like this idea better

### CODE REVIEW

**Comment by STPv22** [comment]
add backshots--backport, I mean, of the key event I'm lazy

**Comment by OeildeLynx31** [comment]
Maybe make that there is a way to open it, but not that the mod menu is automatically opened on launch.

**Comment by STPv22** [comment]
ye but I kinda like this idea better than opening GUI on crash

**Comment by ZXMushroom63** [comment]
this would probably be a good addition, can you make it halt initialization of the client while the gui is initially open?

**Comment by ZXMushroom63** [comment]
Merging, I'll finish off the rest of the changes in order to make this work.

**Comment by STPv22** [comment]
bet

**Pull request merged**
