### PR TITLE
Bettered the worldedit mod

### PR DESCRIPTION
**Pull request by OeildeLynx31**
* Added mod metadata
* Added enchanting effect to the wooden axe => This is throwing an error on applying an enchant that does'nt have a valid name, please fix it

### CODE REVIEW

**Comment by ZXMushroom63** [comment]
don't request a review from me, it's your mod @radmanplays

**Comment by OeildeLynx31** [comment]
@radmanplays

**Comment by ZXMushroom63** [comment]
@OeildeLynx31 for crafting, see updated libcustomitems featureset:
https://github.com/eaglerforge/EaglerForgeInjector/blob/df75615ea7504a37a53e2e24adc0ec5774993f6a/examplemods/CustomItemsDemo.js#L40

**Comment by OeildeLynx31** [comment]
> @OeildeLynx31 for crafting, see updated libcustomitems featureset:
> https://github.com/eaglerforge/EaglerForgeInjector/blob/df75615ea7504a37a53e2e24adc0ec5774993f6a/examplemods/CustomItemsDemo.js#L40

Thanks

**Pull request merged**
